/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import java.awt.HeadlessException;
import static java.lang.System.exit;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

/**
 *
 * @author admin
 */
public class gymInterface extends javax.swing.JFrame {
        Connection con=null;
        Statement st=null;
          ResultSet rs =null;
          PreparedStatement pstmnt= null;
          PreparedStatement pstmnt1= null;
          DefaultTableModel dm;
          Statement stmnt=null;
          int ch=-1;
        
  
    public gymInterface() {
        initComponents();
         try{
             
    Class.forName("oracle.jdbc.driver.OracleDriver");
            
          con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","yogitha123");
          
        } 
   catch(Exception e)
   { JOptionPane.showMessageDialog(null,e);
   
   }
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        caddr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phno = new javax.swing.JTextField();
        sexcb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        trid = new javax.swing.JTextField();
        trname = new javax.swing.JTextField();
        trno = new javax.swing.JTextField();
        trsal = new javax.swing.JTextField();
        grptrainerrb = new javax.swing.JRadioButton();
        pertrainerrb = new javax.swing.JRadioButton();
        spltrainerrb = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        ppid = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ptype = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        dur = new javax.swing.JTextField();
        pamt = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        memcid = new javax.swing.JTextField();
        memname = new javax.swing.JTextField();
        memtype = new javax.swing.JTextField();
        memprice = new javax.swing.JTextField();
        memdoj = new javax.swing.JTextField();
        memdoe = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        trainerid123 = new javax.swing.JTextField();
        pid123 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        noe = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        eqtype = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        clcn = new javax.swing.JTextField();
        cltid = new javax.swing.JTextField();
        clst = new javax.swing.JTextField();
        clet = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        var1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        customertable = new javax.swing.JTable();
        var2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        trainertable = new javax.swing.JTable();
        var3 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        membershiptable = new javax.swing.JTable();
        var4 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        packagetable = new javax.swing.JTable();
        var5 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        equipmenttable = new javax.swing.JTable();
        var6 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        classtable = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        contable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        qtn = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        qmntable = new javax.swing.JTable();
        tname1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        qme = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        qmentable = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        del = new javax.swing.JTextField();
        cust = new javax.swing.JRadioButton();
        trainer = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CUSTOMER ID");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 100, 140, 19);
        jPanel2.add(cid);
        cid.setBounds(550, 90, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUSTOMER NAME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(280, 160, 140, 19);
        jPanel2.add(cname);
        cname.setBounds(550, 150, 204, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SEX");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(280, 220, 103, 19);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(24, 184, 0, 0);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOCALITY");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(280, 300, 100, 19);
        jPanel2.add(caddr);
        caddr.setBounds(550, 300, 204, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTACT NUMBER");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(280, 370, 150, 19);
        jPanel2.add(phno);
        phno.setBounds(550, 370, 204, 30);

        sexcb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        sexcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        sexcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexcbActionPerformed(evt);
            }
        });
        jPanel2.add(sexcb);
        sexcb.setBounds(550, 220, 110, 30);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(36, 259, 0, 0);

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jButton3.setText("SUBMIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(430, 430, 100, 27);

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\gym images\\cus.jpg")); // NOI18N
        jPanel2.add(jLabel35);
        jLabel35.setBounds(30, 20, 880, 470);

        jTabbedPane2.addTab("CUSTOMER", jPanel2);

        jPanel4.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 102));
        jLabel15.setText("TRAINER ID");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(220, 60, 100, 19);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setText("TRAINER NAME");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(220, 120, 120, 19);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("CONTACT NUMBER");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(220, 190, 160, 19);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setText("SALARY");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(230, 260, 80, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 102));
        jLabel19.setText("TRAINER TYPE");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(230, 330, 140, 30);
        jPanel4.add(trid);
        trid.setBounds(460, 50, 140, 30);
        jPanel4.add(trname);
        trname.setBounds(460, 110, 140, 30);
        jPanel4.add(trno);
        trno.setBounds(460, 180, 140, 30);
        jPanel4.add(trsal);
        trsal.setBounds(460, 250, 140, 30);

        grptrainerrb.setBackground(new java.awt.Color(255, 255, 255));
        grptrainerrb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        grptrainerrb.setForeground(new java.awt.Color(255, 255, 255));
        grptrainerrb.setText("Group ");
        grptrainerrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grptrainerrbActionPerformed(evt);
            }
        });
        jPanel4.add(grptrainerrb);
        grptrainerrb.setBounds(460, 320, 180, 27);

        pertrainerrb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        pertrainerrb.setForeground(new java.awt.Color(255, 255, 255));
        pertrainerrb.setText("Personal ");
        pertrainerrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pertrainerrbActionPerformed(evt);
            }
        });
        jPanel4.add(pertrainerrb);
        pertrainerrb.setBounds(460, 350, 180, 27);

        spltrainerrb.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        spltrainerrb.setForeground(new java.awt.Color(255, 255, 255));
        spltrainerrb.setText("Specialized ");
        spltrainerrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spltrainerrbActionPerformed(evt);
            }
        });
        jPanel4.add(spltrainerrb);
        spltrainerrb.setBounds(460, 380, 180, 27);

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jButton5.setText("SUBMIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(350, 440, 100, 27);

        jLabel33.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\t.jpg")); // NOI18N
        jPanel4.add(jLabel33);
        jLabel33.setBounds(20, 10, 1010, 490);

        jTabbedPane2.addTab("TRAINER", jPanel4);

        jPanel9.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("PACKAGE ID");
        jPanel9.add(jLabel20);
        jLabel20.setBounds(320, 70, 120, 30);
        jPanel9.add(ppid);
        ppid.setBounds(680, 70, 89, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("PACKAGE TYPE");
        jPanel9.add(jLabel22);
        jLabel22.setBounds(320, 120, 140, 30);

        ptype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptypeActionPerformed(evt);
            }
        });
        jPanel9.add(ptype);
        ptype.setBounds(620, 120, 210, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("DURATION");
        jPanel9.add(jLabel23);
        jLabel23.setBounds(330, 330, 110, 19);
        jPanel9.add(dur);
        dur.setBounds(680, 320, 130, 30);
        jPanel9.add(pamt);
        pamt.setBounds(680, 370, 130, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jButton7.setText("SUBMIT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7);
        jButton7.setBounds(480, 430, 100, 27);

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("PACKAGE AMOUNT");
        jPanel9.add(jLabel43);
        jLabel43.setBounds(320, 380, 160, 20);

        jLabel37.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\bodybuilding.jpg")); // NOI18N
        jPanel9.add(jLabel37);
        jLabel37.setBounds(20, 10, 910, 500);

        jTabbedPane2.addTab("PACKAGE", jPanel9);

        jPanel3.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setText("CUSTOMER ID");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(220, 60, 130, 19);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setText("MEMBERSHIP NAME");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(220, 110, 160, 19);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel11.setText("MEMBERSHIP TYPE");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(220, 160, 170, 19);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel12.setText("PRICE");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(250, 260, 80, 19);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel13.setText("DATE OF JOIN");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(140, 220, 150, 19);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel14.setText("PACKAGE ID");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(250, 310, 140, 19);

        memcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memcidActionPerformed(evt);
            }
        });
        jPanel3.add(memcid);
        memcid.setBounds(450, 50, 120, 30);
        jPanel3.add(memname);
        memname.setBounds(450, 100, 120, 30);
        jPanel3.add(memtype);
        memtype.setBounds(450, 150, 180, 30);
        jPanel3.add(memprice);
        memprice.setBounds(460, 260, 180, 30);
        jPanel3.add(memdoj);
        memdoj.setBounds(330, 210, 140, 30);
        jPanel3.add(memdoe);
        memdoe.setBounds(720, 210, 140, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(370, 420, 130, 27);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setText("TRAINER ID");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(250, 370, 140, 19);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel24.setText("DATE OF EXPIRY");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(550, 220, 140, 19);

        trainerid123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerid123ActionPerformed(evt);
            }
        });
        jPanel3.add(trainerid123);
        trainerid123.setBounds(460, 370, 180, 30);

        pid123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pid123ActionPerformed(evt);
            }
        });
        jPanel3.add(pid123);
        pid123.setBounds(460, 310, 180, 30);

        jLabel36.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\equip1.jpg")); // NOI18N
        jPanel3.add(jLabel36);
        jLabel36.setBounds(20, 0, 980, 500);

        jTabbedPane2.addTab("MEMBERSHIP", jPanel3);

        jPanel5.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("NUMBER OF EQUIPMENTS");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(270, 110, 220, 19);
        jPanel5.add(noe);
        noe.setBounds(580, 110, 70, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("EQUIPMENT TYPE");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(270, 190, 220, 20);
        jPanel5.add(eqtype);
        eqtype.setBounds(570, 190, 220, 30);

        jButton9.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jButton9.setText("SUBMIT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(450, 350, 110, 27);

        jLabel38.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\equip2.jpg")); // NOI18N
        jPanel5.add(jLabel38);
        jLabel38.setBounds(30, 0, 920, 510);

        jTabbedPane2.addTab("EQUIPMENTS", jPanel5);

        jPanel6.setLayout(null);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 153));
        jLabel29.setText("CLASS NAME");
        jPanel6.add(jLabel29);
        jLabel29.setBounds(260, 80, 110, 19);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 153));
        jLabel30.setText("TRAINER ID");
        jPanel6.add(jLabel30);
        jLabel30.setBounds(260, 150, 100, 19);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 153));
        jLabel31.setText("STARTING TIME");
        jPanel6.add(jLabel31);
        jLabel31.setBounds(260, 220, 130, 19);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 153));
        jLabel32.setText("ENDING TIME");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(260, 280, 120, 19);
        jPanel6.add(clcn);
        clcn.setBounds(520, 70, 170, 30);
        jPanel6.add(cltid);
        cltid.setBounds(520, 140, 170, 30);
        jPanel6.add(clst);
        clst.setBounds(520, 210, 170, 30);
        jPanel6.add(clet);
        clet.setBounds(520, 280, 170, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);
        jButton2.setBounds(400, 420, 110, 27);

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\cust1.jpg")); // NOI18N
        jPanel6.add(jLabel34);
        jLabel34.setBounds(10, 0, 920, 510);

        jTabbedPane2.addTab("CLASS LIST", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("INSERTION", jPanel1);

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton4.setText("VIEW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        customertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(customertable);

        javax.swing.GroupLayout var1Layout = new javax.swing.GroupLayout(var1);
        var1.setLayout(var1Layout);
        var1Layout.setHorizontalGroup(
            var1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var1Layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jButton4)
                .addContainerGap(589, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, var1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        var1Layout.setVerticalGroup(
            var1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jTabbedPane3.addTab("CUSTOMER", var1);

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton6.setText("VIEW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        trainertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(trainertable);

        javax.swing.GroupLayout var2Layout = new javax.swing.GroupLayout(var2);
        var2.setLayout(var2Layout);
        var2Layout.setHorizontalGroup(
            var2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var2Layout.createSequentialGroup()
                .addGroup(var2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(var2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(var2Layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(jButton6)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        var2Layout.setVerticalGroup(
            var2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        jTabbedPane3.addTab("TRAINER", var2);

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton8.setText("VIEW");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        membershiptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(membershiptable);

        javax.swing.GroupLayout var3Layout = new javax.swing.GroupLayout(var3);
        var3.setLayout(var3Layout);
        var3Layout.setHorizontalGroup(
            var3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var3Layout.createSequentialGroup()
                .addGroup(var3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(var3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 908, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(var3Layout.createSequentialGroup()
                        .addGap(492, 492, 492)
                        .addComponent(jButton8)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        var3Layout.setVerticalGroup(
            var3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("MEMBERSHIP", var3);

        jButton10.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton10.setText("VIEW");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        packagetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(packagetable);

        javax.swing.GroupLayout var4Layout = new javax.swing.GroupLayout(var4);
        var4.setLayout(var4Layout);
        var4Layout.setHorizontalGroup(
            var4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var4Layout.createSequentialGroup()
                .addGroup(var4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(var4Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(var4Layout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(jButton10)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        var4Layout.setVerticalGroup(
            var4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("PACKAGE", var4);

        jButton11.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton11.setText("VIEW");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        equipmenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(equipmenttable);

        javax.swing.GroupLayout var5Layout = new javax.swing.GroupLayout(var5);
        var5.setLayout(var5Layout);
        var5Layout.setHorizontalGroup(
            var5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var5Layout.createSequentialGroup()
                .addGroup(var5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(var5Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(var5Layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(jButton11)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        var5Layout.setVerticalGroup(
            var5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("EQUIPMENTS", var5);

        jButton12.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton12.setText("VIEW");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        classtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(classtable);

        javax.swing.GroupLayout var6Layout = new javax.swing.GroupLayout(var6);
        var6.setLayout(var6Layout);
        var6Layout.setHorizontalGroup(
            var6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var6Layout.createSequentialGroup()
                .addGroup(var6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(var6Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(var6Layout.createSequentialGroup()
                        .addGap(489, 489, 489)
                        .addComponent(jButton12)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        var6Layout.setVerticalGroup(
            var6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(var6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("CLASS LIST", var6);

        jButton13.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jButton13.setText("VIEW");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        contable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(contable);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton13)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("CONNECTIONS", jPanel10);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane1.addTab("DISPLAY", jPanel8);

        jPanel14.setLayout(null);
        jPanel14.add(qtn);
        qtn.setBounds(410, 70, 170, 40);

        jButton15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton15.setText("SUBMIT");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton15);
        jButton15.setBounds(670, 70, 140, 40);

        qmntable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(qmntable);

        jPanel14.add(jScrollPane8);
        jScrollPane8.setBounds(70, 150, 950, 310);

        tname1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tname1.setText("TRAINER NAME");
        jPanel14.add(tname1);
        tname1.setBounds(220, 70, 100, 20);
        jPanel14.add(jLabel39);
        jLabel39.setBounds(10, 10, 980, 450);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("QUERY 1", jPanel13);

        jLabel42.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel42.setText("MEMBERSHIP NAME");

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jToggleButton1.setText("SUBMIT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        qmentable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(qmentable);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(qme, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qme, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("QUERY 2", jPanel15);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("QUERIES", jPanel7);

        jPanel11.setLayout(null);

        delete.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        delete.setText("SUBMIT");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel11.add(delete);
        delete.setBounds(530, 190, 110, 27);

        id.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        id.setText("ID");
        jPanel11.add(id);
        id.setBounds(530, 130, 140, 19);

        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel11.add(del);
        del.setBounds(720, 130, 100, 30);

        cust.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cust.setText("CUSTOMER");
        cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custActionPerformed(evt);
            }
        });
        jPanel11.add(cust);
        cust.setBounds(420, 40, 120, 27);

        trainer.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        trainer.setText("TRAINER");
        trainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerActionPerformed(evt);
            }
        });
        jPanel11.add(trainer);
        trainer.setBounds(720, 40, 120, 27);

        jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\gym images\\del1.jpg")); // NOI18N
        jPanel11.add(jLabel8);
        jLabel8.setBounds(0, 0, 1110, 530);

        jTabbedPane1.addTab("DELETION", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            dm=(DefaultTableModel)customertable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            dm.addColumn("CUSTOMER ID");
            dm.addColumn("CUSTOMER NAME");
            dm.addColumn("SEX");
            dm.addColumn("LOCALITY");
            dm.addColumn("CONTACT NUMBER");
             stmnt= con.createStatement();
            rs=stmnt.executeQuery("select * from customer");
            while(rs.next())
            {
                String sarray[]={rs.getString("cid"),rs.getString("cname"),rs.getString("sex"),rs.getString("caddr"),rs.getString("cphno")};
                dm.addRow(sarray);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try{
            dm=(DefaultTableModel)classtable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            
            dm.addColumn("CLASS NAME");
            dm.addColumn("TRAINER ID");
            dm.addColumn("STARTING TIME");
            dm.addColumn("ENDING TIME");
            stmnt= con.createStatement();
            rs=stmnt.executeQuery("select * from class_list");
            while(rs.next())
            {
                String sarray[]={rs.getString("class_name"),rs.getString("tid"),rs.getString("starting_time"),rs.getString("ending_time")};
                dm.addRow(sarray);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try{
            dm=(DefaultTableModel)equipmenttable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            dm.addColumn("NUMBER OF EQUIPMENTS");
            dm.addColumn("EQUIPMENT TYPE");
            
            stmnt= con.createStatement();
            rs=stmnt.executeQuery("select * from equipment order by noe");
            while(rs.next())
            {
                String sarray[]={rs.getString("noe"),rs.getString("equip_type")};
                dm.addRow(sarray);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try{
            dm=(DefaultTableModel)packagetable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            dm.addColumn("PACKAGE ID");
            
            dm.addColumn("PACKAGE TYPE");
            dm.addColumn("DURATION");
            dm.addColumn("PACKAGE AMOUNT");
            stmnt= con.createStatement();
            rs=stmnt.executeQuery("select * from package");
            while(rs.next())
            {
                String sarray[]={rs.getString("pid"),rs.getString("ptype"),rs.getString("duration"),rs.getString("pamt")};
                dm.addRow(sarray);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try{
            dm=(DefaultTableModel)membershiptable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            dm.addColumn("CUSTOMER ID");
            dm.addColumn("MEMBERSHIP NAME");
            dm.addColumn("MEMBERSHIP TYPE");
            dm.addColumn("PRICE");
            dm.addColumn("DATE OF JOIN");
            dm.addColumn("DATE OF EXPIRY");
            stmnt= con.createStatement();
            rs=stmnt.executeQuery("select * from membership");
            while(rs.next())
            {
                String sarray[]={rs.getString("cid"),rs.getString("mname"),rs.getString("mtype"),rs.getString("amount"),rs.getString("doj"),rs.getString("expiry")};
                dm.addRow(sarray);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            dm=(DefaultTableModel)trainertable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            dm.addColumn("TRAINER ID");
            dm.addColumn("TRAINER NAME");
            dm.addColumn("CONTACT NUMBER");
            dm.addColumn("SALARY");
            dm.addColumn("TRAINER TYPE");
       stmnt= con.createStatement();
            rs=stmnt.executeQuery("select * from trainer");
            while(rs.next())
            {
                String sarray[]={rs.getString("tid"),rs.getString("tname"),rs.getString("tphno"),rs.getString("salary"),rs.getString("ttype")};
                dm.addRow(sarray);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s="insert into class_list values(?,?,?,?)";
        try
        {
            pstmnt=con.prepareStatement(s);
            
            pstmnt.setString(1,clcn.getText());
            pstmnt.setString(2,cltid.getText());
            pstmnt.setString(3,clst.getText());
            pstmnt.setString(4,clet.getText());
            pstmnt.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String s="{call insertequip(?,?)}";
        try{
            CallableStatement cst=con.prepareCall(s);
            cst.setString(1,noe.getText());
            cst.setString(2,eqtype.getText());
            
            cst.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted using stored procedure");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String s="insert into package values(?,?,?,?)";
        try{
            pstmnt = con.prepareStatement(s);
            pstmnt.setString(1,ppid.getText());           
            pstmnt.setString(2,ptype.getText());
            pstmnt.setString(3,dur.getText());
            pstmnt.setString(4,pamt.getText());
            pstmnt.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void ptypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptypeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String s="insert into trainer values(?,?,?,?,?)";
        try{
            pstmnt = con.prepareStatement(s);
            pstmnt.setString(1,trid.getText());
            pstmnt.setString(2,trname.getText());
            pstmnt.setString(3,trno.getText());
            pstmnt.setString(4,trsal.getText());
            if(grptrainerrb.isSelected())
            {
                pstmnt.setString(5,"group trainer");
            }
            else if(pertrainerrb.isSelected())
            {
                pstmnt.setString(5,"personal trainer");
            }
            else
            { pstmnt.setString(5, "Specailized Trainer");}
            int saba = Integer.parseInt(trsal.getText());
            if(saba>45000)
            {JOptionPane.showMessageDialog(null,"Trigger executed");
            
            }
            pstmnt.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void spltrainerrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spltrainerrbActionPerformed
        if(spltrainerrb.isSelected())
        {
            pertrainerrb.setSelected(false);
            grptrainerrb.setSelected(false);

        }     // TODO add your handling code here:
    }//GEN-LAST:event_spltrainerrbActionPerformed

    private void pertrainerrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pertrainerrbActionPerformed
        if(pertrainerrb.isSelected())
        {
            grptrainerrb.setSelected(false);
            spltrainerrb.setSelected(false);

        }
    }//GEN-LAST:event_pertrainerrbActionPerformed

    private void grptrainerrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grptrainerrbActionPerformed
        if(grptrainerrb.isSelected())
        {
            pertrainerrb.setSelected(false);
            spltrainerrb.setSelected(false);

        }
    }//GEN-LAST:event_grptrainerrbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s="insert into membership values(?,?,?,?,?,?)";
        String s1="insert into connectiontable values(?,?,?)";
        try{ pstmnt1 = con.prepareStatement(s1);
            pstmnt = con.prepareStatement(s);
            pstmnt.setString(1,memcid.getText());
            pstmnt.setString(2,memname.getText());
            pstmnt.setString(3,memtype.getText());
            pstmnt.setString(4,memprice.getText());
            pstmnt.setString(5,memdoj.getText());
            pstmnt.setString(6,memdoe.getText());
            pstmnt1.setString(1,memcid.getText());
            pstmnt1.setString(2,trainerid123.getText());
            pstmnt1.setString(3,pid123.getText());
            
            pstmnt.executeUpdate();
                pstmnt1.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void memcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memcidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memcidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String s =" insert into customer values(?,?,?,?,?)";
        try{
            pstmnt = con.prepareStatement(s);
            pstmnt.setString(1,cid.getText());
            pstmnt.setString(2,cname.getText());
            if(sexcb.getSelectedIndex()==0)
            { pstmnt.setString(3,"Male");
            }
            else if(sexcb.getSelectedIndex()==1)
            { pstmnt.setString(3,"Female");
            }
            else
            pstmnt.setString(3,"Others");
            pstmnt.setString(4,caddr.getText());
            pstmnt.setString(5,phno.getText());
            
            pstmnt.executeUpdate();
            JOptionPane.showMessageDialog(null,"inserted");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void sexcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexcbActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       String s="";
        if(ch==0)
        {
        s="select * from customer where cid='"+del.getText()+"'";
        }
        else if(ch==1)
        {
         s="select * from trainer where tid='"+del.getText()+"'";
        }
        try
       {
           pstmnt=con.prepareStatement(s);
           rs=pstmnt.executeQuery();
           if(rs.next())
           {
      
               String sql;
        if(cust.isSelected())
        {
            id.setText("CUSTOMER ID:");
        sql="delete from customer where cid=?";
        try{
            pstmnt=con.prepareStatement(sql);
            pstmnt.setString(1,del.getText());
            pstmnt.executeUpdate();
            JOptionPane.showMessageDialog(null,"1 row deleted");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        }
        else
        {
            id.setText("TRAINER ID :");
            sql="delete from trainer where tid=?";
            try{
            pstmnt=con.prepareStatement(sql);
            pstmnt.setString(1,del.getText());
            pstmnt.executeUpdate();
            JOptionPane.showMessageDialog(null,"1 row deleted");
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
            
        }
       }
           else
               JOptionPane.showMessageDialog(null,toUpperCase(del.getText()+" invalid id!"),"ERROR",JOptionPane.ERROR_MESSAGE);
       }
       catch(Exception E)
       {
           JOptionPane.showMessageDialog(null,E,"ERROR",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_deleteActionPerformed

    private void custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custActionPerformed
if(cust.isSelected())
{   id.setText("CUSTOMER ID:");
    trainer.setSelected(false);
    ch=0;
}
    }//GEN-LAST:event_custActionPerformed

    private void trainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerActionPerformed
    if(trainer.isSelected())
    {id.setText("TRAINER ID :");
    cust.setSelected(false);
    ch=1;
    }
    }//GEN-LAST:event_trainerActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void trainerid123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerid123ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainerid123ActionPerformed

    private void pid123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pid123ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pid123ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try{
            dm=(DefaultTableModel)contable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            
            dm.addColumn("CID");
            dm.addColumn("PID");
            dm.addColumn("TID");
            stmnt= con.createStatement();
            rs=stmnt.executeQuery("select * from connectiontable");
            while(rs.next())
            {
                String sarray[]={rs.getString("cid"),rs.getString("pid"),rs.getString("tid")};
                dm.addRow(sarray);
            }
            }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
            
            
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try{
            dm=(DefaultTableModel)qmentable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            dm.addColumn("CUSTOMER ID");
            dm.addColumn("CUSTOMER NAME");
            dm.addColumn("LOCALITY");
            dm.addColumn("CONTACT NUMBER");
            dm.addColumn("MEMBERSHIP NAME");
            stmnt= con.createStatement();
            rs=stmnt.executeQuery("select c.cid,c.cname,c.caddr,c.cphno,m.mname from customer c,membership m where c.cid=m.cid and mname='"+qme.getText()+"'");
            while(rs.next())
            {
                String sarray[]={rs.getString("cid"),rs.getString("cname"),rs.getString("caddr"),rs.getString("cphno"),rs.getString("mname")};
                dm.addRow(sarray);
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try{
            dm=(DefaultTableModel)qmntable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            dm.addColumn("CUSTOMER ID");
            dm.addColumn("CUSTOMER NAME");
            dm.addColumn("CONTACT NUMBER");
            dm.addColumn("TRAINER ID");
            dm.addColumn("TRAINER NAME");
            stmnt= con.createStatement();
            rs=stmnt.executeQuery("select c.cid,c.cname,c.cphno,t.tid,t.tname from customer c,trainer t,connectiontable ct where ct.cid=c.cid and ct.tid=t.tid and tname='"+qtn.getText()+"'");

            while(rs.next())
            {
                String sarray[]={rs.getString("cid"),rs.getString("cname"),rs.getString("cphno"),rs.getString("tid"),rs.getString("tname")};
                dm.addRow(sarray);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton15ActionPerformed
/*  */ 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gymInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gymInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gymInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gymInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gymInterface().setVisible(false);
                new loginframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caddr;
    private javax.swing.JTextField cid;
    private javax.swing.JTable classtable;
    private javax.swing.JTextField clcn;
    private javax.swing.JTextField clet;
    private javax.swing.JTextField clst;
    private javax.swing.JTextField cltid;
    private javax.swing.JTextField cname;
    private javax.swing.JTable contable;
    private javax.swing.JRadioButton cust;
    private javax.swing.JTable customertable;
    private javax.swing.JTextField del;
    private javax.swing.JButton delete;
    private javax.swing.JTextField dur;
    private javax.swing.JTextField eqtype;
    private javax.swing.JTable equipmenttable;
    private javax.swing.JRadioButton grptrainerrb;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable membershiptable;
    private javax.swing.JTextField memcid;
    private javax.swing.JTextField memdoe;
    private javax.swing.JTextField memdoj;
    private javax.swing.JTextField memname;
    private javax.swing.JTextField memprice;
    private javax.swing.JTextField memtype;
    private javax.swing.JTextField noe;
    private javax.swing.JTable packagetable;
    private javax.swing.JTextField pamt;
    private javax.swing.JRadioButton pertrainerrb;
    private javax.swing.JTextField phno;
    private javax.swing.JTextField pid123;
    private javax.swing.JTextField ppid;
    private javax.swing.JTextField ptype;
    private javax.swing.JTextField qme;
    private javax.swing.JTable qmentable;
    private javax.swing.JTable qmntable;
    private javax.swing.JTextField qtn;
    private javax.swing.JComboBox<String> sexcb;
    private javax.swing.JRadioButton spltrainerrb;
    private javax.swing.JLabel tname1;
    private javax.swing.JRadioButton trainer;
    private javax.swing.JTextField trainerid123;
    private javax.swing.JTable trainertable;
    private javax.swing.JTextField trid;
    private javax.swing.JTextField trname;
    private javax.swing.JTextField trno;
    private javax.swing.JTextField trsal;
    private javax.swing.JPanel var1;
    private javax.swing.JPanel var2;
    private javax.swing.JPanel var3;
    private javax.swing.JPanel var4;
    private javax.swing.JPanel var5;
    private javax.swing.JPanel var6;
    // End of variables declaration//GEN-END:variables
}
